In [11]:
import pandas as pd
import numpy as np

In [12]:
conso = pd.read_csv("data/conso_energie_2024.xls", sep="\t", encoding="latin1")

In [13]:
conso.columns

Index(['Périmètre', 'Nature', 'Date', 'Heures', 'Consommation',
       'Prévision J-1', 'Prévision J', 'Fioul', 'Charbon', 'Gaz', 'Nucléaire',
       'Eolien', 'Solaire', 'Hydraulique', 'Pompage', 'Bioénergies',
       'Ech. physiques', 'Taux de Co2', 'Ech. comm. Angleterre',
       'Ech. comm. Espagne', 'Ech. comm. Italie', 'Ech. comm. Suisse',
       'Ech. comm. Allemagne-Belgique', 'Fioul - TAC', 'Fioul - Cogén.',
       'Fioul - Autres', 'Gaz - TAC', 'Gaz - Cogén.', 'Gaz - CCG',
       'Gaz - Autres', 'Hydraulique - Fil de l?eau + éclusée',
       'Hydraulique - Lacs', 'Hydraulique - STEP turbinage',
       'Bioénergies - Déchets', 'Bioénergies - Biomasse',
       'Bioénergies - Biogaz', ' Stockage batterie', 'Déstockage batterie',
       'Eolien terrestre', 'Eolien offshore'],
      dtype='str')

In [14]:
conso = conso.shift(axis=1)
conso["Périmètre"] = conso.index
conso.head(1)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
France,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,...,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0

In [15]:
conso = conso.reset_index()
conso = conso.drop(["index"], axis=1)
conso.head(1)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,...,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0

In [17]:
conso.head()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,...,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,...,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,...,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0

There is a missing value in `Consommation` every 15 min, by starting at 00:00

In [19]:
conso[conso["Consommation"].isnull()]

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
1,France,Données définitives,2024-01-01,00:15,NaN,54300.0,53400.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,France,Données définitives,2024-01-01,00:45,NaN,53200.0,51950.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,France,Données définitives,2024-01-01,01:15,NaN,52900.0,51500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,France,Données définitives,2024-01-01,01:45,NaN,52650.0,51850.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,France,Données définitives,2024-01-01,02:15,NaN,51850.0,51450.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35129,France,Données définitives,2024-12-31,22:15,NaN,61250.0,61500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35131,France,Données définitives,2024-12-31,22:45,NaN,62950.0,63100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35133,France,Données définitives,2024-12-31,23:15,NaN,64500.0,64550.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35135,France,Données définitives,2024-12-31,23:45,NaN,64400.0,64500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35136,RTE ne pourra être tenu responsable de l'usage...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We can observe that the energy consumption numbers are listed every 30 minutes.  
So we'll remove the other rows.

In [29]:
conso = conso[conso["Consommation"].notna()]
conso.info()

<class 'pandas.DataFrame'>
RangeIndex: 17568 entries, 0 to 35134
Data columns (total 40 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Périmètre                             17568 non-null  str
 1   Nature                                17568 non-null  str
 2   Date                                  17568 non-null  str
 3   Heures                                17568 non-null  str
 4   Consommation                          17568 non-null  float64
 5   Prévision J-1                         17568 non-null  float64
 6   Prévision J                           17568 non-null  float64
 7   Fioul                                 17568 non-null  float64
 8   Charbon                               17568 non-null  float64
 9   Gaz                                   17568 non-null  float64
 10  Nucléaire                             17568 non-null  float64
 11  Eolien                                17568 non-null  float64
 12  Solaire                               17568 non-null  float64
 13  Hydraulique                           17568 non-null  float64
 14  Pompage                               17568 non-null  float64
 15  Bioénergies                           17568 non-null  float64
 16  Ech. physiques                        17568 non-null  float64
 17  Taux de Co2                           17568 non-null  float64
 18  Ech. comm. Angleterre                 17568 non-null  float64
 19  Ech. comm. Espagne                    17568 non-null  float64
 20  Ech. comm. Italie                     17568 non-null  float64
 21  Ech. comm. Suisse                     17568 non-null  float64
 22  Ech. comm. Allemagne-Belgique         17568 non-null  float64
 23  Fioul - TAC                           17568 non-null  float64
 24  Fioul - Cogén.                        17568 non-null  float64
 25  Fioul - Autres                        17568 non-null  float64
 26  Gaz - TAC                             17568 non-null  float64
 27  Gaz - Cogén.                          17568 non-null  float64
 28  Gaz - CCG                             17568 non-null  float64
 29  Gaz - Autres                          17568 non-null  float64
 30  Hydraulique - Fil de l?eau + éclusée  17568 non-null  float64
 31  Hydraulique - Lacs                    17568 non-null  float64
 32  Hydraulique - STEP turbinage          17568 non-null  float64
 33  Bioénergies - Déchets                 17568 non-null  float64
 34  Bioénergies - Biomasse                17568 non-null  float64
 35  Bioénergies - Biogaz                  17568 non-null  float64
 36   Stockage batterie                    17568 non-null  float64
 37  Déstockage batterie                   17568 non-null  float64
 38  Eolien terrestre                      17568 non-null  float64
 39  Eolien offshore                       17568 non-null  float64
dtypes: float64(36), str(4)
memory usage: 5.4 MB

In [30]:
conso.head()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2024-01-01,00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,...,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
2,France,Données définitives,2024-01-01,00:30,55167.0,53600.0,52600.0,98.0,17.0,1926.0,...,4928.0,1599.0,6.0,501.0,369.0,347.0,0.0,0.0,14888.0,579.0
4,France,Données définitives,2024-01-01,01:00,53183.0,52800.0,51300.0,96.0,17.0,1987.0,...,4909.0,1293.0,6.0,506.0,373.0,347.0,0.0,0.0,14830.0,581.0
6,France,Données définitives,2024-01-01,01:30,53165.0,53000.0,51700.0,97.0,17.0,1969.0,...,5009.0,1191.0,6.0,506.0,375.0,346.0,0.0,0.0,14656.0,581.0
8,France,Données définitives,2024-01-01,02:00,53088.0,52300.0,52000.0,97.0,17.0,2007.0,...,5104.0,1152.0,5.0,506.0,379.0,345.0,0.0,0.0,14465.0,580.0

In [32]:
conso_live = pd.read_csv("data/conso_live.xls", sep="\t", encoding="latin1")

In [35]:
conso_live.tail(20)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
France,Données temps réel,2026-03-30,19:15,NaN,56650.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,19:30,NaN,57300.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,19:45,NaN,57350.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,20:00,NaN,57400.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,20:15,NaN,57450.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,20:30,NaN,57500.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,20:45,NaN,57000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,21:00,NaN,56500.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,21:15,NaN,55900.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,21:30,NaN,55300.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,21:45,NaN,54450.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,22:00,NaN,53600.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,22:15,NaN,53700.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,22:30,NaN,53800.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,22:45,NaN,54600.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,23:00,NaN,55400.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,23:15,NaN,55100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,23:30,NaN,54800.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données temps réel,2026-03-30,23:45,NaN,54250.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"RTE ne pourra être tenu responsable de l'usage qui pourrait être fait des données mises à disposition, ni en cas de prévisions qui se révèleraient imprécises.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
meteo_75 = pd.read_csv("data/weather/meteo75.csv", sep=";")

In [55]:
list(meteo_75.columns)

['NUM_POSTE', 'NOM_USUEL', 'LAT', 'LON', 'ALTI', 'AAAAMMJJHHMN', 'RR', 'QRR']

In [56]:
meteo_75.head(3)

   NUM_POSTE   NOM_USUEL        LAT       LON  ALTI  AAAAMMJJHHMN   RR  QRR
0   75106001  LUXEMBOURG  48.844667  2.333833    46  202001010000  0.0    9
1   75106001  LUXEMBOURG  48.844667  2.333833    46  202001010006  0.0    9
2   75106001  LUXEMBOURG  48.844667  2.333833    46  202001010012  0.0    9

In [57]:
print(len(meteo75))

496112

In [59]:
meteo_75.info()

<class 'pandas.DataFrame'>
RangeIndex: 1753832 entries, 0 to 1753831
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   NUM_POSTE     int64
 1   NOM_USUEL     str
 2   LAT           float64
 3   LON           float64
 4   ALTI          int64
 5   AAAAMMJJHHMN  int64
 6   RR            float64
 7   QRR           int64
dtypes: float64(3), int64(4), str(1)
memory usage: 107.0 MB