In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import requests
import os
import pandas as pd
import numpy as np
import sys
from pathlib import Path
sys.path.append(os.path.abspath(".."))
import src.raw_preprocessing as rp
import src.feature_engineering as fe
import src.create_dataset as cd
from datetime import date, datetime, timedelta
from vacances_scolaires_france import SchoolHolidayDates

import openmeteo_requests
import requests_cache
from retry_requests import retry

In [70]:
df = pd.read_parquet("../data/final_datasets/datasets_linear_models/conso_v3_linear.parquet")

In [71]:
df.head()

,Consommation,Zone_A,Zone_B,Zone_C,Vacances de la Toussaint,Vacances de Noël,Vacances d'Hiver,Vacances de Printemps,Vacances d'Été,public_holidays,...,is_weekend_x_season_Summer,is_holiday_x_season_Summer,hour_x_season_Winter,is_weekend_x_season_Winter,is_holiday_x_season_Winter,temp_x_humidity,temp_x_wind,humidity_x_wind,HDD,CDD
336,76986.0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,-23.625160,-0.448757,158.664136,18.258496,0.0
337,75624.0,0,0,0,0,0,0,0,0,0,...,0,0,0.5,0,0,-51.046198,-1.881718,307.182089,18.559192,0.0
338,73317.0,0,0,0,0,0,0,0,0,0,...,0,0,1.0,0,0,-78.401620,-1.624052,172.203081,18.859888,0.0
339,74096.0,0,0,0,0,0,0,0,0,0,...,0,0,1.5,0,0,-60.000035,-2.217065,306.450364,18.658847,0.0
340,73854.0,0,0,0,0,0,0,0,0,0,...,0,0,2.0,0,0,-41.642012,-0.884911,175.819505,18.457807,0.0

In [72]:
df.columns

Index(['Consommation', 'Zone_A', 'Zone_B', 'Zone_C',
       'Vacances de la Toussaint', 'Vacances de Noël', 'Vacances d'Hiver',
       'Vacances de Printemps', 'Vacances d'Été', 'public_holidays', '44T',
       '69T', '59T', '75T', '13T', '33T', 'T', 'U', 'FF', 'PMER', 'RR1',
       'year', 'month', 'hour', 'day_of_week', 'is_weekend', 'hour_sin',
       'hour_cos', 'day_of_week_sin', 'day_of_week_cos', 'month_sin',
       'month_cos', 'lagged_1', 'lagged_2', 'lagged_48', 'lagged_336',
       'rolling_mean_24h', 'rolling_std_24h', 'rolling_mean_7d',
       'rolling_std_7d', 'rolling_max_24h', 'rolling_min_24h',
       'consumption_diff_1', 'consumption_diff_48', 'consumption_pct_change_1',
       'consumption_pct_change_48', 'season_Spring', 'season_Summer',
       'season_Winter', 'temp_sq', 'humidity_sq', 'hour_x_is_weekend',
       'hour_x_is_holiday', 'hour_x_dow', 'hour_x_month', 'is_weekend_x_month',
       'is_holiday_x_month', 'hour_x_temp', 'hour_x_humidity', 'hour_x_wind',
       'is_weekend_x_temp', 'is_holiday_x_temp', 'month_x_temp', 'dow_x_temp',
       'hour_x_temp_sq', 'is_weekend_x_temp_sq', 'season_Spring_x_temp',
       'season_Summer_x_temp', 'season_Winter_x_temp', 'hour_x_season_Spring',
       'is_weekend_x_season_Spring', 'is_holiday_x_season_Spring',
       'hour_x_season_Summer', 'is_weekend_x_season_Summer',
       'is_holiday_x_season_Summer', 'hour_x_season_Winter',
       'is_weekend_x_season_Winter', 'is_holiday_x_season_Winter',
       'temp_x_humidity', 'temp_x_wind', 'humidity_x_wind', 'HDD', 'CDD'],
      dtype='object')

In [91]:
cd.download_monthly_data()

conso_energie_2026.zip already exists

In [5]:
df = rp.conso_preprocess(Path("../data/conso/real_time_conso/"))

df = df[df["Heures"].apply(lambda x: x.minute in {00, 30})]

df = df.reset_index(drop=True)
df.loc[len(df)] = None

In [6]:
df = fe.lagged_consumption(df)

In [7]:
df

,Date,Heures,Consommation,lagged_1,lagged_2,lagged_48,lagged_336
0,2026-05-01,00:00:00,41688.0,NaN,NaN,NaN,NaN
1,2026-05-01,00:30:00,40393.0,41688.0,NaN,NaN,NaN
2,2026-05-01,01:00:00,38108.0,40393.0,41688.0,NaN,NaN
3,2026-05-01,01:30:00,37744.0,38108.0,40393.0,NaN,NaN
4,2026-05-01,02:00:00,36708.0,37744.0,38108.0,NaN,NaN
...,...,...,...,...,...,...,...
3818,2026-07-19,13:00:00,42182.0,42953.0,41863.0,46948.0,45512.0
3819,2026-07-19,13:30:00,41187.0,42182.0,42953.0,46739.0,44682.0
3820,2026-07-19,14:00:00,41283.0,41187.0,42182.0,46889.0,44856.0
3821,2026-07-19,14:30:00,41408.0,41283.0,41187.0,46745.0,45452.0
3822,NaN,NaN,NaN,41408.0,41283.0,46359.0,44998.0

In [8]:
t = df["Heures"].iloc[-2]

new_time = (
    datetime.combine(datetime.today(), t)
    + timedelta(minutes=30)
).time()

In [9]:
df.loc[len(df)-1, "Heures"] = new_time

In [10]:
df.loc[len(df)-1, "Date"] = datetime.today().strftime('%Y-%m-%d')

In [11]:
df

,Date,Heures,Consommation,lagged_1,lagged_2,lagged_48,lagged_336
0,2026-05-01,00:00:00,41688.0,NaN,NaN,NaN,NaN
1,2026-05-01,00:30:00,40393.0,41688.0,NaN,NaN,NaN
2,2026-05-01,01:00:00,38108.0,40393.0,41688.0,NaN,NaN
3,2026-05-01,01:30:00,37744.0,38108.0,40393.0,NaN,NaN
4,2026-05-01,02:00:00,36708.0,37744.0,38108.0,NaN,NaN
...,...,...,...,...,...,...,...
3818,2026-07-19,13:00:00,42182.0,42953.0,41863.0,46948.0,45512.0
3819,2026-07-19,13:30:00,41187.0,42182.0,42953.0,46739.0,44682.0
3820,2026-07-19,14:00:00,41283.0,41187.0,42182.0,46889.0,44856.0
3821,2026-07-19,14:30:00,41408.0,41283.0,41187.0,46745.0,45452.0
3822,2026-07-30,15:00:00,NaN,41408.0,41283.0,46359.0,44998.0

#### Adding the name of the holidays

In [101]:
from pprint import pprint
today = date(2026, 5, 16).isoformat()

url = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-calendrier-scolaire/records"

params = {
    "where": f"start_date <= date'{today}' AND end_date >= date'{today}' AND zones = 'Zone C'"
}

response = requests.get(url, params=params)

In [12]:
#Adding the infos about the holidays
today = date.today().isoformat()
url = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-calendrier-scolaire/records"

zones = ['A', 'B', 'C']
vacances = ['vacances de la toussaint', 'vacances de noël', "vacances d'hiver",'vacances de printemps', "vacances d'été"]
feries = [
    "jour de l'an",
    "lundi de pâques",
    "fête du travail",
    "victoire 1945",
    "ascension",
    "lundi de pentecôte",
    "fête nationale",
    "assomption",
    "toussaint",
    "armistice",
    "noël",
    "pont de l'ascension",
]

#finished_with_holidays = False
df.loc[:, "public_holidays"] = 0
df.loc[:, "Vacances de la Toussaint"] = 0
df.loc[:, "Vacances de Noël"] = 0
df.loc[:, "Vacances d'Hiver"] = 0
df.loc[:, "Vacances de Printemps"] = 0
df.loc[:, "Vacances d'Été"] = 0

for z in zones:
    params = {
        "where": f"start_date <= date'{today}' AND end_date >= date'{today}' AND zones = 'Zone {z}'"
    }
    response = requests.get(url, params=params).json()
    # If no holidays we set the columns with the value 0
    if response["total_count"] == 0:
        continue

    else : 
        
        for event in response["results"]:
            # We check if it's school holidays
            if event["description"].lower() in vacances:
                if event["description"].lower() == "vacances de la toussaint":
                    df.loc[:, "Vacances de la Toussaint"] = 1
                    
                elif event["description"].lower() == "vacances de noël":
                    df.loc[:, "Vacances de Noël"] = 1
                    
                elif event["description"].lower() == "vacances d'hiver":
                    df.loc[:, "Vacances d'Hiver"] = 1
                    
                elif event["description"].lower() == "vacances de printemps":
                    df.loc[:, "Vacances de Printemps"] = 1

                elif event["description"].lower() == "vacances d'été":
                    df.loc[:, "Vacances d'Été"] = 1
            # Or if it's public holidays (jours fériés)
            elif event in feries:
                df.loc[:, "public_holidays"] = 1

In [13]:
df

,Date,Heures,Consommation,lagged_1,lagged_2,lagged_48,lagged_336,public_holidays,Vacances de la Toussaint,Vacances de Noël,Vacances d'Hiver,Vacances de Printemps,Vacances d'Été
0,2026-05-01,00:00:00,41688.0,NaN,NaN,NaN,NaN,0,0,0,0,0,1
1,2026-05-01,00:30:00,40393.0,41688.0,NaN,NaN,NaN,0,0,0,0,0,1
2,2026-05-01,01:00:00,38108.0,40393.0,41688.0,NaN,NaN,0,0,0,0,0,1
3,2026-05-01,01:30:00,37744.0,38108.0,40393.0,NaN,NaN,0,0,0,0,0,1
4,2026-05-01,02:00:00,36708.0,37744.0,38108.0,NaN,NaN,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3818,2026-07-19,13:00:00,42182.0,42953.0,41863.0,46948.0,45512.0,0,0,0,0,0,1
3819,2026-07-19,13:30:00,41187.0,42182.0,42953.0,46739.0,44682.0,0,0,0,0,0,1
3820,2026-07-19,14:00:00,41283.0,41187.0,42182.0,46889.0,44856.0,0,0,0,0,0,1
3821,2026-07-19,14:30:00,41408.0,41283.0,41187.0,46745.0,45452.0,0,0,0,0,0,1
3822,2026-07-30,15:00:00,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,1

In [14]:
df = fe.date_and_hour_pred(df)
df = fe.cyclical_encoding(df)
df = fe.rolling_window(df)
df = fe.lagged_trend(df)

In [15]:
row = df.iloc[-1]
row

Consommation                                 NaN
lagged_1                                 41408.0
lagged_2                                 41283.0
lagged_48                                46359.0
lagged_336                               44998.0
public_holidays                                0
Vacances de la Toussaint                       0
Vacances de Noël                               0
Vacances d'Hiver                               0
Vacances de Printemps                          0
Vacances d'Été                                 1
full_date                    2026-07-30 15:00:00
year                                        2026
month                                          7
hour                                        15.0
day_of_week                                    3
is_weekend                                     0
hour_sin                               -0.707107
hour_cos                               -0.707107
day_of_week_sin                         0.433884
day_of_week_cos                        -0.900969
month_sin                                   -0.5
month_cos                              -0.866025
rolling_mean_24h                    40340.479167
rolling_std_24h                      4656.129417
rolling_mean_7d                      45952.77381
rolling_std_7d                       5955.083204
rolling_max_24h                          46374.0
rolling_min_24h                          33277.0
consumption_diff_1                         125.0
consumption_diff_48                      -5337.0
consumption_pct_change_1                0.003028
consumption_pct_change_48              -0.114173
Name: 3822, dtype: object

In [16]:
pred = pd.DataFrame([row] * 10)

In [17]:
pred["full_date"] = row["full_date"] + pd.to_timedelta(range(10), unit="m") * 30

In [18]:
pred["full_date"].iloc[-1]

Timestamp('2026-07-30 19:30:00')

In [19]:
pred

,Consommation,lagged_1,lagged_2,lagged_48,lagged_336,public_holidays,Vacances de la Toussaint,Vacances de Noël,Vacances d'Hiver,Vacances de Printemps,...,rolling_mean_24h,rolling_std_24h,rolling_mean_7d,rolling_std_7d,rolling_max_24h,rolling_min_24h,consumption_diff_1,consumption_diff_48,consumption_pct_change_1,consumption_pct_change_48
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173
3822,NaN,41408.0,41283.0,46359.0,44998.0,0,0,0,0,0,...,40340.479167,4656.129417,45952.77381,5955.083204,46374.0,33277.0,125.0,-5337.0,0.003028,-0.114173

#### We'll add the temperature for each hour and interpolate the values for the hours with this format : hh:30

### RTE France API

In [86]:
id_client = "863fa354-33b4-4bf6-a844-3dd668062f92"
id_secret = "83b2284d-b40f-4627-916f-d35473030cbf"
url = "https://digital.iservices.rte-france.com/token/oauth/"

response = requests.post(url, auth=(id_client, id_secret))

In [87]:
response.json()

{'access_token': 'k474YPtYGg8Im6fzkvcoIUeWaPI4fzxRjj6ankSZK5EghTijE48cHG',
 'token_type': 'Bearer',
 'expires_in': 3600}

In [88]:
token = response.json()["access_token"]
headers = {
    "Authorization" : f"Bearer {token}"
}

url = "https://digital.iservices.rte-france.com/open_api/consumption/v1/short_term"

data = requests.get(url, headers=headers)

In [89]:
data.json()

{'short_term': [{'type': 'REALISED',
   'start_date': '2026-07-17T00:00:00+02:00',
   'end_date': '2026-07-18T00:00:00+02:00',
   'values': [{'start_date': '2026-07-17T00:00:00+02:00',
     'end_date': '2026-07-17T00:15:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 47387},
    {'start_date': '2026-07-17T00:15:00+02:00',
     'end_date': '2026-07-17T00:30:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 46988},
    {'start_date': '2026-07-17T00:30:00+02:00',
     'end_date': '2026-07-17T00:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45765},
    {'start_date': '2026-07-17T00:45:00+02:00',
     'end_date': '2026-07-17T01:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44762},
    {'start_date': '2026-07-17T01:00:00+02:00',
     'end_date': '2026-07-17T01:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43709},
    {'start_date': '2026-07-17T01:15:00+02:00',
     'end_date': '2026-07-17T01:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43931},
    {'start_date': '2026-07-17T01:30:00+02:00',
     'end_date': '2026-07-17T01:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43462},
    {'start_date': '2026-07-17T01:45:00+02:00',
     'end_date': '2026-07-17T02:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43431},
    {'start_date': '2026-07-17T02:00:00+02:00',
     'end_date': '2026-07-17T02:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42545},
    {'start_date': '2026-07-17T02:15:00+02:00',
     'end_date': '2026-07-17T02:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42257},
    {'start_date': '2026-07-17T02:30:00+02:00',
     'end_date': '2026-07-17T02:45:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 41407},
    {'start_date': '2026-07-17T02:45:00+02:00',
     'end_date': '2026-07-17T03:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40947},
    {'start_date': '2026-07-17T03:00:00+02:00',
     'end_date': '2026-07-17T03:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40345},
    {'start_date': '2026-07-17T03:15:00+02:00',
     'end_date': '2026-07-17T03:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39952},
    {'start_date': '2026-07-17T03:30:00+02:00',
     'end_date': '2026-07-17T03:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39647},
    {'start_date': '2026-07-17T03:45:00+02:00',
     'end_date': '2026-07-17T04:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39399},
    {'start_date': '2026-07-17T04:00:00+02:00',
     'end_date': '2026-07-17T04:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39237},
    {'start_date': '2026-07-17T04:15:00+02:00',
     'end_date': '2026-07-17T04:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39245},
    {'start_date': '2026-07-17T04:30:00+02:00',
     'end_date': '2026-07-17T04:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39136},
    {'start_date': '2026-07-17T04:45:00+02:00',
     'end_date': '2026-07-17T05:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39122},
    {'start_date': '2026-07-17T05:00:00+02:00',
     'end_date': '2026-07-17T05:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39063},
    {'start_date': '2026-07-17T05:15:00+02:00',
     'end_date': '2026-07-17T05:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39861},
    {'start_date': '2026-07-17T05:30:00+02:00',
     'end_date': '2026-07-17T05:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40382},
    {'start_date': '2026-07-17T05:45:00+02:00',
     'end_date': '2026-07-17T06:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40749},
    {'start_date': '2026-07-17T06:00:00+02:00',
     'end_date': '2026-07-17T06:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40911},
    {'start_date': '2026-07-17T06:15:00+02:00',
     'end_date': '2026-07-17T06:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41465},
    {'start_date': '2026-07-17T06:30:00+02:00',
     'end_date': '2026-07-17T06:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41945},
    {'start_date': '2026-07-17T06:45:00+02:00',
     'end_date': '2026-07-17T07:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42430},
    {'start_date': '2026-07-17T07:00:00+02:00',
     'end_date': '2026-07-17T07:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43040},
    {'start_date': '2026-07-17T07:15:00+02:00',
     'end_date': '2026-07-17T07:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43578},
    {'start_date': '2026-07-17T07:30:00+02:00',
     'end_date': '2026-07-17T07:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44293},
    {'start_date': '2026-07-17T07:45:00+02:00',
     'end_date': '2026-07-17T08:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44849},
    {'start_date': '2026-07-17T08:00:00+02:00',
     'end_date': '2026-07-17T08:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45518},
    {'start_date': '2026-07-17T08:15:00+02:00',
     'end_date': '2026-07-17T08:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46264},
    {'start_date': '2026-07-17T08:30:00+02:00',
     'end_date': '2026-07-17T08:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47061},
    {'start_date': '2026-07-17T08:45:00+02:00',
     'end_date': '2026-07-17T09:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47627},
    {'start_date': '2026-07-17T09:00:00+02:00',
     'end_date': '2026-07-17T09:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48191},
    {'start_date': '2026-07-17T09:15:00+02:00',
     'end_date': '2026-07-17T09:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48803},
    {'start_date': '2026-07-17T09:30:00+02:00',
     'end_date': '2026-07-17T09:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49196},
    {'start_date': '2026-07-17T09:45:00+02:00',
     'end_date': '2026-07-17T10:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49711},
    {'start_date': '2026-07-17T10:00:00+02:00',
     'end_date': '2026-07-17T10:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 49948},
    {'start_date': '2026-07-17T10:15:00+02:00',
     'end_date': '2026-07-17T10:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50412},
    {'start_date': '2026-07-17T10:30:00+02:00',
     'end_date': '2026-07-17T10:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50970},
    {'start_date': '2026-07-17T10:45:00+02:00',
     'end_date': '2026-07-17T11:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51134},
    {'start_date': '2026-07-17T11:00:00+02:00',
     'end_date': '2026-07-17T11:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51354},
    {'start_date': '2026-07-17T11:15:00+02:00',
     'end_date': '2026-07-17T11:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51637},
    {'start_date': '2026-07-17T11:30:00+02:00',
     'end_date': '2026-07-17T11:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51865},
    {'start_date': '2026-07-17T11:45:00+02:00',
     'end_date': '2026-07-17T12:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51887},
    {'start_date': '2026-07-17T12:00:00+02:00',
     'end_date': '2026-07-17T12:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52289},
    {'start_date': '2026-07-17T12:15:00+02:00',
     'end_date': '2026-07-17T12:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52659},
    {'start_date': '2026-07-17T12:30:00+02:00',
     'end_date': '2026-07-17T12:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52947},
    {'start_date': '2026-07-17T12:45:00+02:00',
     'end_date': '2026-07-17T13:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53654},
    {'start_date': '2026-07-17T13:00:00+02:00',
     'end_date': '2026-07-17T13:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53416}]},
  {'type': 'ID',
   'start_date': '2026-07-17T00:00:00+02:00',
   'end_date': '2026-07-18T00:00:00+02:00',
   'values': [{'start_date': '2026-07-17T00:00:00+02:00',
     'end_date': '2026-07-17T00:15:00+02:00',
     'updated_date': '2026-07-16T23:54:15+02:00',
     'value': 48200},
    {'start_date': '2026-07-17T00:30:00+02:00',
     'end_date': '2026-07-17T00:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45300},
    {'start_date': '2026-07-17T00:45:00+02:00',
     'end_date': '2026-07-17T01:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46750},
    {'start_date': '2026-07-17T01:00:00+02:00',
     'end_date': '2026-07-17T01:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43500},
    {'start_date': '2026-07-17T01:15:00+02:00',
     'end_date': '2026-07-17T01:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43850},
    {'start_date': '2026-07-17T01:30:00+02:00',
     'end_date': '2026-07-17T01:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 44200},
    {'start_date': '2026-07-17T01:45:00+02:00',
     'end_date': '2026-07-17T02:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43300},
    {'start_date': '2026-07-17T02:00:00+02:00',
     'end_date': '2026-07-17T02:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42400},
    {'start_date': '2026-07-17T02:15:00+02:00',
     'end_date': '2026-07-17T02:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 41750},
    {'start_date': '2026-07-17T02:30:00+02:00',
     'end_date': '2026-07-17T02:45:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 41100},
    {'start_date': '2026-07-17T02:45:00+02:00',
     'end_date': '2026-07-17T03:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40550},
    {'start_date': '2026-07-17T03:00:00+02:00',
     'end_date': '2026-07-17T03:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40000},
    {'start_date': '2026-07-17T03:15:00+02:00',
     'end_date': '2026-07-17T03:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39800},
    {'start_date': '2026-07-17T03:30:00+02:00',
     'end_date': '2026-07-17T03:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39600},
    {'start_date': '2026-07-17T03:45:00+02:00',
     'end_date': '2026-07-17T04:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39400},
    {'start_date': '2026-07-17T04:00:00+02:00',
     'end_date': '2026-07-17T04:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39200},
    {'start_date': '2026-07-17T04:15:00+02:00',
     'end_date': '2026-07-17T04:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39150},
    {'start_date': '2026-07-17T04:30:00+02:00',
     'end_date': '2026-07-17T04:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39100},
    {'start_date': '2026-07-17T04:45:00+02:00',
     'end_date': '2026-07-17T05:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39000},
    {'start_date': '2026-07-17T05:00:00+02:00',
     'end_date': '2026-07-17T05:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 38900},
    {'start_date': '2026-07-17T05:15:00+02:00',
     'end_date': '2026-07-17T05:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39800},
    {'start_date': '2026-07-17T05:30:00+02:00',
     'end_date': '2026-07-17T05:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40700},
    {'start_date': '2026-07-17T05:45:00+02:00',
     'end_date': '2026-07-17T06:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40950},
    {'start_date': '2026-07-17T06:00:00+02:00',
     'end_date': '2026-07-17T06:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41200},
    {'start_date': '2026-07-17T06:15:00+02:00',
     'end_date': '2026-07-17T06:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41650},
    {'start_date': '2026-07-17T06:30:00+02:00',
     'end_date': '2026-07-17T06:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42100},
    {'start_date': '2026-07-17T06:45:00+02:00',
     'end_date': '2026-07-17T07:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42750},
    {'start_date': '2026-07-17T07:00:00+02:00',
     'end_date': '2026-07-17T07:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43400},
    {'start_date': '2026-07-17T07:15:00+02:00',
     'end_date': '2026-07-17T07:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44000},
    {'start_date': '2026-07-17T07:30:00+02:00',
     'end_date': '2026-07-17T07:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44600},
    {'start_date': '2026-07-17T07:45:00+02:00',
     'end_date': '2026-07-17T08:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45300},
    {'start_date': '2026-07-17T08:00:00+02:00',
     'end_date': '2026-07-17T08:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46000},
    {'start_date': '2026-07-17T08:15:00+02:00',
     'end_date': '2026-07-17T08:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46550},
    {'start_date': '2026-07-17T08:30:00+02:00',
     'end_date': '2026-07-17T08:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47100},
    {'start_date': '2026-07-17T08:45:00+02:00',
     'end_date': '2026-07-17T09:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47800},
    {'start_date': '2026-07-17T09:00:00+02:00',
     'end_date': '2026-07-17T09:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48500},
    {'start_date': '2026-07-17T09:15:00+02:00',
     'end_date': '2026-07-17T09:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48950},
    {'start_date': '2026-07-17T09:30:00+02:00',
     'end_date': '2026-07-17T09:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49400},
    {'start_date': '2026-07-17T09:45:00+02:00',
     'end_date': '2026-07-17T10:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 49700},
    {'start_date': '2026-07-17T10:00:00+02:00',
     'end_date': '2026-07-17T10:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50000},
    {'start_date': '2026-07-17T10:15:00+02:00',
     'end_date': '2026-07-17T10:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50550},
    {'start_date': '2026-07-17T10:30:00+02:00',
     'end_date': '2026-07-17T10:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51100},
    {'start_date': '2026-07-17T10:45:00+02:00',
     'end_date': '2026-07-17T11:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51250},
    {'start_date': '2026-07-17T11:00:00+02:00',
     'end_date': '2026-07-17T11:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51400},
    {'start_date': '2026-07-17T11:15:00+02:00',
     'end_date': '2026-07-17T11:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51650},
    {'start_date': '2026-07-17T11:30:00+02:00',
     'end_date': '2026-07-17T11:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51900},
    {'start_date': '2026-07-17T11:45:00+02:00',
     'end_date': '2026-07-17T12:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52200},
    {'start_date': '2026-07-17T12:00:00+02:00',
     'end_date': '2026-07-17T12:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52500},
    {'start_date': '2026-07-17T12:15:00+02:00',
     'end_date': '2026-07-17T12:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52250},
    {'start_date': '2026-07-17T12:30:00+02:00',
     'end_date': '2026-07-17T12:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52000},
    {'start_date': '2026-07-17T12:45:00+02:00',
     'end_date': '2026-07-17T13:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52650},
    {'start_date': '2026-07-17T13:00:00+02:00',
     'end_date': '2026-07-17T13:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53300},
    {'start_date': '2026-07-17T13:15:00+02:00',
     'end_date': '2026-07-17T13:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52700},
    {'start_date': '2026-07-17T13:30:00+02:00',
     'end_date': '2026-07-17T13:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52100},
    {'start_date': '2026-07-17T13:45:00+02:00',
     'end_date': '2026-07-17T14:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52000},
    {'start_date': '2026-07-17T14:00:00+02:00',
     'end_date': '2026-07-17T14:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51900},
    {'start_date': '2026-07-17T14:15:00+02:00',
     'end_date': '2026-07-17T14:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52850},
    {'start_date': '2026-07-17T14:30:00+02:00',
     'end_date': '2026-07-17T14:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53800},
    {'start_date': '2026-07-17T14:45:00+02:00',
     'end_date': '2026-07-17T15:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53400},
    {'start_date': '2026-07-17T15:00:00+02:00',
     'end_date': '2026-07-17T15:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53000},
    {'start_date': '2026-07-17T15:15:00+02:00',
     'end_date': '2026-07-17T15:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52550},
    {'start_date': '2026-07-17T15:30:00+02:00',
     'end_date': '2026-07-17T15:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52100},
    {'start_date': '2026-07-17T15:45:00+02:00',
     'end_date': '2026-07-17T16:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51800},
    {'start_date': '2026-07-17T16:00:00+02:00',
     'end_date': '2026-07-17T16:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51500},
    {'start_date': '2026-07-17T16:15:00+02:00',
     'end_date': '2026-07-17T16:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51300},
    {'start_date': '2026-07-17T16:30:00+02:00',
     'end_date': '2026-07-17T16:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',

### Open-Meteo API

In [21]:
# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://api.open-meteo.com/v1/forecast"
lat_long = {
    '13': {'ville': 'Marseille', 'latitude': 43.2965, 'longitude': 5.3698},     # Bouches-du-Rhône
    '33': {'ville': 'Bordeaux',  'latitude': 44.8378, 'longitude': -0.5792},    # Gironde
    '44': {'ville': 'Nantes',    'latitude': 47.2184, 'longitude': -1.5536},    # Loire-Atlantique
    '59': {'ville': 'Lille',     'latitude': 50.6292, 'longitude': 3.0573},     # Nord
    '69': {'ville': 'Lyon',      'latitude': 45.7640, 'longitude': 4.8357},     # Rhône
    '75': {'ville': 'Paris',     'latitude': 48.8566, 'longitude': 2.3522},     # Paris
}

for k, v in lat_long.items():
    
    params = {
    	"latitude": v["latitude"],
    	"longitude": v["longitude"],
    	"hourly": ["temperature_2m", "relative_humidity_2m", "rain", "surface_pressure", "wind_speed_10m"],
    	"timezone": "Europe/London",
    	"past_days": 7,
    	"forecast_days": 1,
    }
    responses = openmeteo.weather_api(url, params = params)
    
    # Process first location. Add a for-loop for multiple locations or weather models
    response = responses[0]
    print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
    print(f"Elevation: {response.Elevation()} m asl")
    print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
    print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")
    
    # Process hourly data. The order of variables needs to be the same as requested.
    hourly = response.Hourly()
    hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
    hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
    hourly_rain = hourly.Variables(2).ValuesAsNumpy()
    hourly_surface_pressure = hourly.Variables(3).ValuesAsNumpy()
    hourly_wind_speed_10m = hourly.Variables(4).ValuesAsNumpy()
    
    hourly_data = {
    	"date": pd.date_range(
    		start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
    		end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
    		freq = pd.Timedelta(seconds = hourly.Interval()),
    		inclusive = "left"
    	).tz_convert(response.Timezone().decode())
    }
    
    hourly_data["temperature_2m"] = hourly_temperature_2m
    hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
    hourly_data["rain"] = hourly_rain
    hourly_data["surface_pressure"] = hourly_surface_pressure
    hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
    
    hourly_dataframe = pd.DataFrame(data = hourly_data)
    print("\nHourly data\n", hourly_dataframe)source venv/bin/activate

Coordinates: 43.29999923706055°N 5.369998931884766°E
Elevation: 6.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       29.617001                  44.0   0.0
1   2026-07-21 01:00:00+01:00       29.017000                  45.0   0.0
2   2026-07-21 02:00:00+01:00       27.967001                  43.0   0.0
3   2026-07-21 03:00:00+01:00       27.467001                  47.0   0.0
4   2026-07-21 04:00:00+01:00       26.817001                  45.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       27.017000                  73.0   0.0
188 2026-07-28 20:00:00+01:00       25.667000                  83.0   0.0
189 2026-07-28 21:00:00+01:00       25.167000                  86.0   0.0
190 2026-07-28 22:00:00+01:00       25.667000                  77.0   0.0
191 2026-07-28 23:00:00+01:00       25.667000                  77.0   0.0

     surface_pressure  wind_speed_10m
0         1012.814331        1.835647
1         1013.012390        3.075841
2         1012.512024        8.089993
3         1012.710327        2.902413
4         1012.708374        3.319036
..                ...             ...
187       1017.605408       13.138765
188       1018.001587       11.570515
189       1018.599976        9.504273
190       1019.000916        8.145870
191       1019.300720        6.151683

[192 rows x 6 columns]
Coordinates: 44.84000015258789°N -0.5800001621246338°E
Elevation: 16.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       23.995501                  39.0   0.0
1   2026-07-21 01:00:00+01:00       22.995501                  38.0   0.0
2   2026-07-21 02:00:00+01:00       21.945499                  40.0   0.0
3   2026-07-21 03:00:00+01:00       20.945499                  40.0   0.0
4   2026-07-21 04:00:00+01:00       20.295500                  39.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       33.545502                  33.0   0.0
188 2026-07-28 20:00:00+01:00       32.445503                  37.0   0.0
189 2026-07-28 21:00:00+01:00       29.845499                  44.0   0.0
190 2026-07-28 22:00:00+01:00       28.045500                  50.0   0.0
191 2026-07-28 23:00:00+01:00       26.195499                  56.0   0.0

     surface_pressure  wind_speed_10m
0         1016.328979       13.358861
1         1016.222839       13.450708
2         1016.216064       13.320000
3         1016.010193       12.864649
4         1015.906128       12.181625
..                ...             ...
187       1013.192993        1.080000
188       1013.186340        4.829907
189       1013.669922        3.976330
190       1014.357788        2.520000
191       1014.745667        3.096837

[192 rows x 6 columns]
Coordinates: 47.220001220703125°N -1.5500001907348633°E
Elevation: 19.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       20.437000                  49.0   0.0
1   2026-07-21 01:00:00+01:00       19.636999                  52.0   0.0
2   2026-07-21 02:00:00+01:00       18.886999                  53.0   0.0
3   2026-07-21 03:00:00+01:00       18.437000                  54.0   0.0
4   2026-07-21 04:00:00+01:00       17.786999                  55.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       30.937000                  28.0   0.0
188 2026-07-28 20:00:00+01:00       28.636999                  33.0   0.0
189 2026-07-28 21:00:00+01:00       27.136999                  36.0   0.0
190 2026-07-28 22:00:00+01:00       25.987000                  39.0   0.0
191 2026-07-28 23:00:00+01:00       24.987000                  42.0   0.0

     surface_pressure  wind_speed_10m
0         1020.539612       13.684735
1         1020.630432       13.979872
2         1020.727356       14.058450
3         1021.023804       13.551501
4         1020.719360       13.183080
..                ...             ...
187       1013.434570       14.404499
188       1013.617249       13.320000
189       1014.104858       11.183201
190       1014.395264        9.000000
191       1014.386963        8.825508

[192 rows x 6 columns]
Coordinates: 50.63800048828125°N 3.044999837875366°E
Elevation: 27.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       14.780500                  73.0   0.0
1   2026-07-21 01:00:00+01:00       13.580501                  78.0   0.0
2   2026-07-21 02:00:00+01:00       12.980500                  82.0   0.0
3   2026-07-21 03:00:00+01:00       12.380500                  82.0   0.0
4   2026-07-21 04:00:00+01:00       11.830501                  84.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       31.330500                  25.0   0.0
188 2026-07-28 20:00:00+01:00       27.830500                  44.0   0.0
189 2026-07-28 21:00:00+01:00       26.580500                  47.0   0.0
190 2026-07-28 22:00:00+01:00       24.530499                  53.0   0.0
191 2026-07-28 23:00:00+01:00       23.180500                  54.0   0.0

     surface_pressure  wind_speed_10m
0         1023.018188       10.080000
1         1023.000549        6.480000
2         1022.995667        5.760000
3         1022.991882        6.120000
4         1023.087280        6.840000
..                ...             ...
187       1015.090698        8.280000
188       1014.879822       16.199999
189       1015.161804        9.360000
190       1015.448059        9.720000
191       1015.533447        9.000000

[192 rows x 6 columns]
Coordinates: 45.76000213623047°N 4.839999675750732°E
Elevation: 184.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       22.011000                  36.0   0.0
1   2026-07-21 01:00:00+01:00       21.111000                  39.0   0.0
2   2026-07-21 02:00:00+01:00       20.411001                  40.0   0.0
3   2026-07-21 03:00:00+01:00       19.861000                  42.0   0.0
4   2026-07-21 04:00:00+01:00       19.111000                  42.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       32.960999                  40.0   0.0
188 2026-07-28 20:00:00+01:00       32.510998                  34.0   0.0
189 2026-07-28 21:00:00+01:00       30.061001                  40.0   0.0
190 2026-07-28 22:00:00+01:00       28.711000                  38.0   0.0
191 2026-07-28 23:00:00+01:00       27.311001                  42.0   0.0

     surface_pressure  wind_speed_10m
0          997.669128       13.363711
1          997.408447       13.910169
2          997.064209       12.522619
3          997.318115       12.224107
4          997.067749       11.367109
..                ...             ...
187        995.193237        7.920000
188        995.163208       13.104198
189        995.586304       11.542478
190        996.278137        9.366920
191        996.867126        8.350138

[192 rows x 6 columns]
Coordinates: 48.86000061035156°N 2.359999656677246°E
Elevation: 36.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-21 00:00:00+01:00       17.815001                  52.0   0.0
1   2026-07-21 01:00:00+01:00       17.265001                  54.0   0.0
2   2026-07-21 02:00:00+01:00       16.265001                  58.0   0.0
3   2026-07-21 03:00:00+01:00       15.514999                  64.0   0.0
4   2026-07-21 04:00:00+01:00       15.014999                  67.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-28 19:00:00+01:00       31.415001                  30.0   0.0
188 2026-07-28 20:00:00+01:00       30.965000                  28.0   0.0
189 2026-07-28 21:00:00+01:00       29.865000                  31.0   0.0
190 2026-07-28 22:00:00+01:00       28.565001                  35.0   0.0
191 2026-07-28 23:00:00+01:00       27.165001                  39.0   0.0

     surface_pressure  wind_speed_10m
0         1020.877502       13.441071
1         1020.769897       11.770403
2         1020.256897       11.165805
3         1019.947083        9.904906
4         1020.138550        9.793058
..                ...             ...
187       1012.504761        9.000000
188       1012.498718        6.519877
189       1012.782654        5.506941
190       1012.963989        5.014219
191       1013.044617        4.024922

[192 rows x 6 columns]

In [38]:
# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": 43.2965,
    "longitude": 5.3698,
    "hourly": ["temperature_2m", "relative_humidity_2m", "rain", "surface_pressure", "wind_speed_10m"],
    "timezone": "Europe/London",
    "past_days": 7,
    "forecast_days": 1,
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
hourly_rain = hourly.Variables(2).ValuesAsNumpy()
hourly_surface_pressure = hourly.Variables(3).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(4).ValuesAsNumpy()

hourly_data = {
    "date": pd.date_range(
        start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
        end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = hourly.Interval()),
        inclusive = "left"
    ).tz_convert(response.Timezone().decode())
}

hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["rain"] = hourly_rain
hourly_data["surface_pressure"] = hourly_surface_pressure
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m

hourly_dataframe = pd.DataFrame(data = hourly_data)

Coordinates: 43.29999923706055°N 5.369998931884766°E
Elevation: 6.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

In [23]:
type(hourly_dataframe["date"].iloc[-1])

pandas._libs.tslibs.timestamps.Timestamp

In [35]:
hourly_dataframe

,date,temperature_2m,relative_humidity_2m,rain,surface_pressure,wind_speed_10m
0,2026-07-21 00:00:00+01:00,29.617001,44.0,0.0,1012.814331,1.835647
1,2026-07-21 01:00:00+01:00,29.017000,45.0,0.0,1013.012390,3.075841
2,2026-07-21 02:00:00+01:00,27.967001,43.0,0.0,1012.512024,8.089993
3,2026-07-21 03:00:00+01:00,27.467001,47.0,0.0,1012.710327,2.902413
4,2026-07-21 04:00:00+01:00,26.817001,45.0,0.0,1012.708374,3.319036
...,...,...,...,...,...,...
187,2026-07-28 19:00:00+01:00,27.017000,73.0,0.0,1017.605408,13.138765
188,2026-07-28 20:00:00+01:00,25.667000,83.0,0.0,1018.001587,11.570515
189,2026-07-28 21:00:00+01:00,25.167000,86.0,0.0,1018.599976,9.504273
190,2026-07-28 22:00:00+01:00,25.667000,77.0,0.0,1019.000916,8.145870
191,2026-07-28 23:00:00+01:00,25.667000,77.0,0.0,1019.300720,6.151683

In [34]:
hourly_dataframe["date"].iloc[-1]

Timestamp('2026-07-28 23:00:00+0100', tz='Europe/London')

In [26]:
hourly_dataframe["date"].iloc[-1].to_pydatetime()

datetime.datetime(2026, 7, 28, 23, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>)