In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import requests
import os
import pandas as pd
import numpy as np
import sys
from pathlib import Path
sys.path.append(os.path.abspath(".."))
import src.raw_preprocessing as rp
import src.feature_engineering as fe
import src.create_dataset as cd
from datetime import datetime, timedelta

In [59]:
conso = pd.read_parquet("../data/final_datasets/datasets_linear_models/conso_v3_linear.parquet")

In [60]:
conso.columns

Index(['Consommation', 'Zone_A', 'Zone_B', 'Zone_C',
       'Vacances de la Toussaint', 'Vacances de Noël', 'Vacances d'Hiver',
       'Vacances de Printemps', 'Vacances d'Été', 'public_holidays', '44T',
       '69T', '59T', '75T', '13T', '33T', 'T', 'U', 'FF', 'PMER', 'RR1',
       'year', 'is_weekend', 'hour_sin', 'hour_cos', 'day_of_week_sin',
       'day_of_week_cos', 'month_sin', 'month_cos', 'lagged_1', 'lagged_2',
       'lagged_48', 'lagged_336', 'rolling_mean_24h', 'rolling_std_24h',
       'rolling_mean_7d', 'rolling_std_7d', 'rolling_max_24h',
       'rolling_min_24h', 'consumption_diff_1', 'consumption_diff_48',
       'consumption_pct_change_1', 'consumption_pct_change_48',
       'season_Spring', 'season_Summer', 'season_Winter', 'temp_sq',
       'humidity_sq', 'hour_x_is_weekend', 'hour_x_is_holiday', 'hour_x_dow',
       'hour_x_month', 'is_weekend_x_month', 'is_holiday_x_month',
       'hour_x_temp', 'hour_x_humidity', 'hour_x_wind', 'is_weekend_x_temp',
       'is_holiday_x_temp', 'month_x_temp', 'dow_x_temp', 'hour_x_temp_sq',
       'is_weekend_x_temp_sq', 'season_Spring_x_temp', 'season_Summer_x_temp',
       'season_Winter_x_temp', 'hour_x_season_Spring',
       'is_weekend_x_season_Spring', 'is_holiday_x_season_Spring',
       'hour_x_season_Summer', 'is_weekend_x_season_Summer',
       'is_holiday_x_season_Summer', 'hour_x_season_Winter',
       'is_weekend_x_season_Winter', 'is_holiday_x_season_Winter',
       'temp_x_humidity', 'temp_x_wind', 'humidity_x_wind', 'HDD', 'CDD'],
      dtype='object')

In [ ]:
cd.download_monthly_data()

In [61]:
df = rp.conso_preprocess(Path("../data/conso/real_time_conso/"))

df = df[df["Heures"].apply(lambda x: x.minute in {00, 30})]

df = df.reset_index(drop=True)
df.loc[len(df)] = None

In [62]:
df

            Date    Heures  Consommation
0     2026-05-01  00:00:00       41688.0
1     2026-05-01  00:30:00       40393.0
2     2026-05-01  01:00:00       38108.0
3     2026-05-01  01:30:00       37744.0
4     2026-05-01  02:00:00       36708.0
...          ...       ...           ...
3818  2026-07-19  13:00:00       42182.0
3819  2026-07-19  13:30:00       41187.0
3820  2026-07-19  14:00:00       41283.0
3821  2026-07-19  14:30:00       41408.0
3822         NaN       NaN           NaN

[3823 rows x 3 columns]

In [63]:
df = fe.lagged_consumption(df)

In [64]:
df

,Date,Heures,Consommation,lagged_1,lagged_2,lagged_48,lagged_336
0,2026-05-01,00:00:00,41688.0,NaN,NaN,NaN,NaN
1,2026-05-01,00:30:00,40393.0,41688.0,NaN,NaN,NaN
2,2026-05-01,01:00:00,38108.0,40393.0,41688.0,NaN,NaN
3,2026-05-01,01:30:00,37744.0,38108.0,40393.0,NaN,NaN
4,2026-05-01,02:00:00,36708.0,37744.0,38108.0,NaN,NaN
...,...,...,...,...,...,...,...
3818,2026-07-19,13:00:00,42182.0,42953.0,41863.0,46948.0,45512.0
3819,2026-07-19,13:30:00,41187.0,42182.0,42953.0,46739.0,44682.0
3820,2026-07-19,14:00:00,41283.0,41187.0,42182.0,46889.0,44856.0
3821,2026-07-19,14:30:00,41408.0,41283.0,41187.0,46745.0,45452.0
3822,NaN,NaN,NaN,41408.0,41283.0,46359.0,44998.0

In [65]:
t = df["Heures"].iloc[-2]

new_time = (
    datetime.combine(datetime.today(), t)
    + timedelta(minutes=30)
).time()

In [66]:
new_time

datetime.time(15, 0)

In [67]:
df.loc[len(df)-1, "Heures"] = new_time

In [68]:
df

,Date,Heures,Consommation,lagged_1,lagged_2,lagged_48,lagged_336
0,2026-05-01,00:00:00,41688.0,NaN,NaN,NaN,NaN
1,2026-05-01,00:30:00,40393.0,41688.0,NaN,NaN,NaN
2,2026-05-01,01:00:00,38108.0,40393.0,41688.0,NaN,NaN
3,2026-05-01,01:30:00,37744.0,38108.0,40393.0,NaN,NaN
4,2026-05-01,02:00:00,36708.0,37744.0,38108.0,NaN,NaN
...,...,...,...,...,...,...,...
3818,2026-07-19,13:00:00,42182.0,42953.0,41863.0,46948.0,45512.0
3819,2026-07-19,13:30:00,41187.0,42182.0,42953.0,46739.0,44682.0
3820,2026-07-19,14:00:00,41283.0,41187.0,42182.0,46889.0,44856.0
3821,2026-07-19,14:30:00,41408.0,41283.0,41187.0,46745.0,45452.0
3822,NaN,15:00:00,NaN,41408.0,41283.0,46359.0,44998.0

In [70]:
from datetime import date
from vacances_scolaires_france import SchoolHolidayDates

vacances = SchoolHolidayDates()
today = date.today()

zone_a = vacances.is_holiday_for_zone(today, "A")
zone_b = vacances.is_holiday_for_zone(today, "B")
zone_c = vacances.is_holiday_for_zone(today, "C")

print(f"Zone A : {zone_a}")
print(f"Zone B : {zone_b}")
print(f"Zone C : {zone_c}")

Zone A : True
Zone B : True
Zone C : True

### RTE France API

In [86]:
id_client = "863fa354-33b4-4bf6-a844-3dd668062f92"
id_secret = "83b2284d-b40f-4627-916f-d35473030cbf"
url = "https://digital.iservices.rte-france.com/token/oauth/"

response = requests.post(url, auth=(id_client, id_secret))

In [87]:
response.json()

{'access_token': 'k474YPtYGg8Im6fzkvcoIUeWaPI4fzxRjj6ankSZK5EghTijE48cHG',
 'token_type': 'Bearer',
 'expires_in': 3600}

In [88]:
token = response.json()["access_token"]
headers = {
    "Authorization" : f"Bearer {token}"
}

url = "https://digital.iservices.rte-france.com/open_api/consumption/v1/short_term"

data = requests.get(url, headers=headers)

In [89]:
data.json()

{'short_term': [{'type': 'REALISED',
   'start_date': '2026-07-17T00:00:00+02:00',
   'end_date': '2026-07-18T00:00:00+02:00',
   'values': [{'start_date': '2026-07-17T00:00:00+02:00',
     'end_date': '2026-07-17T00:15:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 47387},
    {'start_date': '2026-07-17T00:15:00+02:00',
     'end_date': '2026-07-17T00:30:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 46988},
    {'start_date': '2026-07-17T00:30:00+02:00',
     'end_date': '2026-07-17T00:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45765},
    {'start_date': '2026-07-17T00:45:00+02:00',
     'end_date': '2026-07-17T01:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44762},
    {'start_date': '2026-07-17T01:00:00+02:00',
     'end_date': '2026-07-17T01:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43709},
    {'start_date': '2026-07-17T01:15:00+02:00',
     'end_date': '2026-07-17T01:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43931},
    {'start_date': '2026-07-17T01:30:00+02:00',
     'end_date': '2026-07-17T01:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43462},
    {'start_date': '2026-07-17T01:45:00+02:00',
     'end_date': '2026-07-17T02:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43431},
    {'start_date': '2026-07-17T02:00:00+02:00',
     'end_date': '2026-07-17T02:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42545},
    {'start_date': '2026-07-17T02:15:00+02:00',
     'end_date': '2026-07-17T02:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42257},
    {'start_date': '2026-07-17T02:30:00+02:00',
     'end_date': '2026-07-17T02:45:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 41407},
    {'start_date': '2026-07-17T02:45:00+02:00',
     'end_date': '2026-07-17T03:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40947},
    {'start_date': '2026-07-17T03:00:00+02:00',
     'end_date': '2026-07-17T03:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40345},
    {'start_date': '2026-07-17T03:15:00+02:00',
     'end_date': '2026-07-17T03:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39952},
    {'start_date': '2026-07-17T03:30:00+02:00',
     'end_date': '2026-07-17T03:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39647},
    {'start_date': '2026-07-17T03:45:00+02:00',
     'end_date': '2026-07-17T04:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39399},
    {'start_date': '2026-07-17T04:00:00+02:00',
     'end_date': '2026-07-17T04:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39237},
    {'start_date': '2026-07-17T04:15:00+02:00',
     'end_date': '2026-07-17T04:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39245},
    {'start_date': '2026-07-17T04:30:00+02:00',
     'end_date': '2026-07-17T04:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39136},
    {'start_date': '2026-07-17T04:45:00+02:00',
     'end_date': '2026-07-17T05:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39122},
    {'start_date': '2026-07-17T05:00:00+02:00',
     'end_date': '2026-07-17T05:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39063},
    {'start_date': '2026-07-17T05:15:00+02:00',
     'end_date': '2026-07-17T05:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39861},
    {'start_date': '2026-07-17T05:30:00+02:00',
     'end_date': '2026-07-17T05:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40382},
    {'start_date': '2026-07-17T05:45:00+02:00',
     'end_date': '2026-07-17T06:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40749},
    {'start_date': '2026-07-17T06:00:00+02:00',
     'end_date': '2026-07-17T06:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40911},
    {'start_date': '2026-07-17T06:15:00+02:00',
     'end_date': '2026-07-17T06:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41465},
    {'start_date': '2026-07-17T06:30:00+02:00',
     'end_date': '2026-07-17T06:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41945},
    {'start_date': '2026-07-17T06:45:00+02:00',
     'end_date': '2026-07-17T07:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42430},
    {'start_date': '2026-07-17T07:00:00+02:00',
     'end_date': '2026-07-17T07:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43040},
    {'start_date': '2026-07-17T07:15:00+02:00',
     'end_date': '2026-07-17T07:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43578},
    {'start_date': '2026-07-17T07:30:00+02:00',
     'end_date': '2026-07-17T07:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44293},
    {'start_date': '2026-07-17T07:45:00+02:00',
     'end_date': '2026-07-17T08:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44849},
    {'start_date': '2026-07-17T08:00:00+02:00',
     'end_date': '2026-07-17T08:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45518},
    {'start_date': '2026-07-17T08:15:00+02:00',
     'end_date': '2026-07-17T08:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46264},
    {'start_date': '2026-07-17T08:30:00+02:00',
     'end_date': '2026-07-17T08:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47061},
    {'start_date': '2026-07-17T08:45:00+02:00',
     'end_date': '2026-07-17T09:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47627},
    {'start_date': '2026-07-17T09:00:00+02:00',
     'end_date': '2026-07-17T09:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48191},
    {'start_date': '2026-07-17T09:15:00+02:00',
     'end_date': '2026-07-17T09:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48803},
    {'start_date': '2026-07-17T09:30:00+02:00',
     'end_date': '2026-07-17T09:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49196},
    {'start_date': '2026-07-17T09:45:00+02:00',
     'end_date': '2026-07-17T10:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49711},
    {'start_date': '2026-07-17T10:00:00+02:00',
     'end_date': '2026-07-17T10:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 49948},
    {'start_date': '2026-07-17T10:15:00+02:00',
     'end_date': '2026-07-17T10:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50412},
    {'start_date': '2026-07-17T10:30:00+02:00',
     'end_date': '2026-07-17T10:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50970},
    {'start_date': '2026-07-17T10:45:00+02:00',
     'end_date': '2026-07-17T11:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51134},
    {'start_date': '2026-07-17T11:00:00+02:00',
     'end_date': '2026-07-17T11:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51354},
    {'start_date': '2026-07-17T11:15:00+02:00',
     'end_date': '2026-07-17T11:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51637},
    {'start_date': '2026-07-17T11:30:00+02:00',
     'end_date': '2026-07-17T11:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51865},
    {'start_date': '2026-07-17T11:45:00+02:00',
     'end_date': '2026-07-17T12:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51887},
    {'start_date': '2026-07-17T12:00:00+02:00',
     'end_date': '2026-07-17T12:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52289},
    {'start_date': '2026-07-17T12:15:00+02:00',
     'end_date': '2026-07-17T12:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52659},
    {'start_date': '2026-07-17T12:30:00+02:00',
     'end_date': '2026-07-17T12:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52947},
    {'start_date': '2026-07-17T12:45:00+02:00',
     'end_date': '2026-07-17T13:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53654},
    {'start_date': '2026-07-17T13:00:00+02:00',
     'end_date': '2026-07-17T13:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53416}]},
  {'type': 'ID',
   'start_date': '2026-07-17T00:00:00+02:00',
   'end_date': '2026-07-18T00:00:00+02:00',
   'values': [{'start_date': '2026-07-17T00:00:00+02:00',
     'end_date': '2026-07-17T00:15:00+02:00',
     'updated_date': '2026-07-16T23:54:15+02:00',
     'value': 48200},
    {'start_date': '2026-07-17T00:30:00+02:00',
     'end_date': '2026-07-17T00:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45300},
    {'start_date': '2026-07-17T00:45:00+02:00',
     'end_date': '2026-07-17T01:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46750},
    {'start_date': '2026-07-17T01:00:00+02:00',
     'end_date': '2026-07-17T01:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43500},
    {'start_date': '2026-07-17T01:15:00+02:00',
     'end_date': '2026-07-17T01:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43850},
    {'start_date': '2026-07-17T01:30:00+02:00',
     'end_date': '2026-07-17T01:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 44200},
    {'start_date': '2026-07-17T01:45:00+02:00',
     'end_date': '2026-07-17T02:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 43300},
    {'start_date': '2026-07-17T02:00:00+02:00',
     'end_date': '2026-07-17T02:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 42400},
    {'start_date': '2026-07-17T02:15:00+02:00',
     'end_date': '2026-07-17T02:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 41750},
    {'start_date': '2026-07-17T02:30:00+02:00',
     'end_date': '2026-07-17T02:45:00+02:00',
     'updated_date': '2026-07-17T13:05:47+02:00',
     'value': 41100},
    {'start_date': '2026-07-17T02:45:00+02:00',
     'end_date': '2026-07-17T03:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40550},
    {'start_date': '2026-07-17T03:00:00+02:00',
     'end_date': '2026-07-17T03:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40000},
    {'start_date': '2026-07-17T03:15:00+02:00',
     'end_date': '2026-07-17T03:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39800},
    {'start_date': '2026-07-17T03:30:00+02:00',
     'end_date': '2026-07-17T03:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39600},
    {'start_date': '2026-07-17T03:45:00+02:00',
     'end_date': '2026-07-17T04:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39400},
    {'start_date': '2026-07-17T04:00:00+02:00',
     'end_date': '2026-07-17T04:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39200},
    {'start_date': '2026-07-17T04:15:00+02:00',
     'end_date': '2026-07-17T04:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39150},
    {'start_date': '2026-07-17T04:30:00+02:00',
     'end_date': '2026-07-17T04:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39100},
    {'start_date': '2026-07-17T04:45:00+02:00',
     'end_date': '2026-07-17T05:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39000},
    {'start_date': '2026-07-17T05:00:00+02:00',
     'end_date': '2026-07-17T05:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 38900},
    {'start_date': '2026-07-17T05:15:00+02:00',
     'end_date': '2026-07-17T05:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 39800},
    {'start_date': '2026-07-17T05:30:00+02:00',
     'end_date': '2026-07-17T05:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40700},
    {'start_date': '2026-07-17T05:45:00+02:00',
     'end_date': '2026-07-17T06:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 40950},
    {'start_date': '2026-07-17T06:00:00+02:00',
     'end_date': '2026-07-17T06:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41200},
    {'start_date': '2026-07-17T06:15:00+02:00',
     'end_date': '2026-07-17T06:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 41650},
    {'start_date': '2026-07-17T06:30:00+02:00',
     'end_date': '2026-07-17T06:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42100},
    {'start_date': '2026-07-17T06:45:00+02:00',
     'end_date': '2026-07-17T07:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 42750},
    {'start_date': '2026-07-17T07:00:00+02:00',
     'end_date': '2026-07-17T07:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 43400},
    {'start_date': '2026-07-17T07:15:00+02:00',
     'end_date': '2026-07-17T07:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44000},
    {'start_date': '2026-07-17T07:30:00+02:00',
     'end_date': '2026-07-17T07:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 44600},
    {'start_date': '2026-07-17T07:45:00+02:00',
     'end_date': '2026-07-17T08:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 45300},
    {'start_date': '2026-07-17T08:00:00+02:00',
     'end_date': '2026-07-17T08:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46000},
    {'start_date': '2026-07-17T08:15:00+02:00',
     'end_date': '2026-07-17T08:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 46550},
    {'start_date': '2026-07-17T08:30:00+02:00',
     'end_date': '2026-07-17T08:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47100},
    {'start_date': '2026-07-17T08:45:00+02:00',
     'end_date': '2026-07-17T09:00:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 47800},
    {'start_date': '2026-07-17T09:00:00+02:00',
     'end_date': '2026-07-17T09:15:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48500},
    {'start_date': '2026-07-17T09:15:00+02:00',
     'end_date': '2026-07-17T09:30:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 48950},
    {'start_date': '2026-07-17T09:30:00+02:00',
     'end_date': '2026-07-17T09:45:00+02:00',
     'updated_date': '2026-07-17T13:05:48+02:00',
     'value': 49400},
    {'start_date': '2026-07-17T09:45:00+02:00',
     'end_date': '2026-07-17T10:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 49700},
    {'start_date': '2026-07-17T10:00:00+02:00',
     'end_date': '2026-07-17T10:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50000},
    {'start_date': '2026-07-17T10:15:00+02:00',
     'end_date': '2026-07-17T10:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 50550},
    {'start_date': '2026-07-17T10:30:00+02:00',
     'end_date': '2026-07-17T10:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51100},
    {'start_date': '2026-07-17T10:45:00+02:00',
     'end_date': '2026-07-17T11:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51250},
    {'start_date': '2026-07-17T11:00:00+02:00',
     'end_date': '2026-07-17T11:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51400},
    {'start_date': '2026-07-17T11:15:00+02:00',
     'end_date': '2026-07-17T11:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51650},
    {'start_date': '2026-07-17T11:30:00+02:00',
     'end_date': '2026-07-17T11:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51900},
    {'start_date': '2026-07-17T11:45:00+02:00',
     'end_date': '2026-07-17T12:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52200},
    {'start_date': '2026-07-17T12:00:00+02:00',
     'end_date': '2026-07-17T12:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52500},
    {'start_date': '2026-07-17T12:15:00+02:00',
     'end_date': '2026-07-17T12:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52250},
    {'start_date': '2026-07-17T12:30:00+02:00',
     'end_date': '2026-07-17T12:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52000},
    {'start_date': '2026-07-17T12:45:00+02:00',
     'end_date': '2026-07-17T13:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52650},
    {'start_date': '2026-07-17T13:00:00+02:00',
     'end_date': '2026-07-17T13:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53300},
    {'start_date': '2026-07-17T13:15:00+02:00',
     'end_date': '2026-07-17T13:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52700},
    {'start_date': '2026-07-17T13:30:00+02:00',
     'end_date': '2026-07-17T13:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52100},
    {'start_date': '2026-07-17T13:45:00+02:00',
     'end_date': '2026-07-17T14:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52000},
    {'start_date': '2026-07-17T14:00:00+02:00',
     'end_date': '2026-07-17T14:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51900},
    {'start_date': '2026-07-17T14:15:00+02:00',
     'end_date': '2026-07-17T14:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52850},
    {'start_date': '2026-07-17T14:30:00+02:00',
     'end_date': '2026-07-17T14:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53800},
    {'start_date': '2026-07-17T14:45:00+02:00',
     'end_date': '2026-07-17T15:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53400},
    {'start_date': '2026-07-17T15:00:00+02:00',
     'end_date': '2026-07-17T15:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 53000},
    {'start_date': '2026-07-17T15:15:00+02:00',
     'end_date': '2026-07-17T15:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52550},
    {'start_date': '2026-07-17T15:30:00+02:00',
     'end_date': '2026-07-17T15:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 52100},
    {'start_date': '2026-07-17T15:45:00+02:00',
     'end_date': '2026-07-17T16:00:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51800},
    {'start_date': '2026-07-17T16:00:00+02:00',
     'end_date': '2026-07-17T16:15:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51500},
    {'start_date': '2026-07-17T16:15:00+02:00',
     'end_date': '2026-07-17T16:30:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',
     'value': 51300},
    {'start_date': '2026-07-17T16:30:00+02:00',
     'end_date': '2026-07-17T16:45:00+02:00',
     'updated_date': '2026-07-17T13:05:49+02:00',

### Open-Meteo API

In [61]:
token_climat = "0qQ6Dilvnsvc1wktvJ5EZdeef1WNy1JVPNGLqWlzBchwzHjP3iMdg"

headers_clim = {
    "Authorization" : f"Bearer {token_climat}"
}

url_temp = "http://www.infoclimat.fr/public-api/gfs/json?_ll=48.85341,2.3488&_auth=U0kCFQ9xASNTflBnAHYDKgJqDjsJfwIlA39QM1g9USxROgNiUjIEYlM9BnsCLQI0VnsPbA41VWUDaFIqCXsHZlM5Am4PZAFmUzxQNQAvAygCMA5uCTUCOANgUDRYKlEtUTMDZ1I0BHhTPQZtAjMCKFZsD2YOL1VoA2JSKgl7B2VTNwJuD2gBYVM8UDMANAM3AjkOcQkpAjwDMVAyWD1RYVEyAzRSMQQyUzQGMgJnAjdWbQ9xDjlVbwNhUj0JZgdlUzACYw9zAXxTRVBBAC0DdwJzDjsJcAInAzVQaVhh&_c=375f0112f9eb404558d62deef26d2dc5"

data_clim = requests.get(url_temp, headers=headers_clim)

In [62]:
data_clim.json()

{'request_state': 200,
 'request_key': 'fd543c77e33d6c8a5e218e948a19e487',
 'message': 'OK',
 'model_run': '02',
 'source': 'internal:GFS:1',
 '2026-07-16 05:00:00': {'temperature': {'2m': 292.3,
   'sol': 292.8,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101710},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 48.8},
  'vent_moyen': {'10m': 8.2},
  'vent_rafales': {'10m': 11.9},
  'vent_direction': {'10m': 375},
  'iso_zero': 3623,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 18}},
 '2026-07-16 08:00:00': {'temperature': {'2m': 294.3,
   'sol': 293.3,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101730},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 47.9},
  'vent_moyen': {'10m': 6},
  'vent_rafales': {'10m': 8.4},
  'vent_direction': {'10m': 383},
  'iso_zero': 3569,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 53}},
 '2026-07-16 11:00:00': {'temperature': {'2m': 301.8,
   'sol': 299.7,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101690},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 35.4},
  'vent_moyen': {'10m': 8.3},
  'vent_rafales': {'10m': 11.2},
  'vent_direction': {'10m': 408},
  'iso_zero': 3645,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 98}},
 '2026-07-16 14:00:00': {'temperature': {'2m': 306.7,
   'sol': 304,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101500},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 21.8},
  'vent_moyen': {'10m': 7.3},
  'vent_rafales': {'10m': 9.2},
  'vent_direction': {'10m': 225},
  'iso_zero': 3596,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 85}},
 '2026-07-16 17:00:00': {'temperature': {'2m': 306.9,
   'sol': 305.3,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101320},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 20.4},
  'vent_moyen': {'10m': 9.2},
  'vent_rafales': {'10m': 11.7},
  'vent_direction': {'10m': 262},
  'iso_zero': 3628,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 99}},
 '2026-07-16 20:00:00': {'temperature': {'2m': 306,
   'sol': 305.6,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101110},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 22.1},
  'vent_moyen': {'10m': 8.7},
  'vent_rafales': {'10m': 6.5},
  'vent_direction': {'10m': 404},
  'iso_zero': 3599,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 70}},
 '2026-07-16 23:00:00': {'temperature': {'2m': 296.1,
   'sol': 296.3,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101380},
  'pluie': 0.4,
  'pluie_convective': 0.3,
  'humidite': {'2m': 59.7},
  'vent_moyen': {'10m': 16.3},
  'vent_rafales': {'10m': 29.4},
  'vent_direction': {'10m': 442},
  'iso_zero': 3756,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 96}},
 '2026-07-17 02:00:00': {'temperature': {'2m': 293,
   'sol': 293.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101340},
  'pluie': 0.2,
  'pluie_convective': 0.3,
  'humidite': {'2m': 77.9},
  'vent_moyen': {'10m': 8.9},
  'vent_rafales': {'10m': 13},
  'vent_direction': {'10m': 388},
  'iso_zero': 3655,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 78}},
 '2026-07-17 05:00:00': {'temperature': {'2m': 292.3,
   'sol': 292.5,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101300},
  'pluie': 0.2,
  'pluie_convective': 0.2,
  'humidite': {'2m': 77.7},
  'vent_moyen': {'10m': 1.7},
  'vent_rafales': {'10m': 6.2},
  'vent_direction': {'10m': 414},
  'iso_zero': 3744,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 92}},
 '2026-07-17 08:00:00': {'temperature': {'2m': 292.4,
   'sol': 291.6,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101370},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 77},
  'vent_moyen': {'10m': 7},
  'vent_rafales': {'10m': 8.7},
  'vent_direction': {'10m': 371},
  'iso_zero': 3632,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 96}},
 '2026-07-17 11:00:00': {'temperature': {'2m': 297.1,
   'sol': 295.3,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101430},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 54.6},
  'vent_moyen': {'10m': 9.5},
  'vent_rafales': {'10m': 9.4},
  'vent_direction': {'10m': 347},
  'iso_zero': 3609,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 99}},
 '2026-07-17 14:00:00': {'temperature': {'2m': 301.7,
   'sol': 299.4,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101390},
  'pluie': 0.2,
  'pluie_convective': 0.2,
  'humidite': {'2m': 39.1},
  'vent_moyen': {'10m': 8.6},
  'vent_rafales': {'10m': 10.2},
  'vent_direction': {'10m': 315},
  'iso_zero': 3588,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 99}},
 '2026-07-17 17:00:00': {'temperature': {'2m': 302.4,
   'sol': 301.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101330},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 36},
  'vent_moyen': {'10m': 16.4},
  'vent_rafales': {'10m': 15.5},
  'vent_direction': {'10m': 332},
  'iso_zero': 3516,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 100}},
 '2026-07-17 20:00:00': {'temperature': {'2m': 300.1,
   'sol': 299.3,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101380},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 36.1},
  'vent_moyen': {'10m': 20.2},
  'vent_rafales': {'10m': 24.1},
  'vent_direction': {'10m': 353},
  'iso_zero': 3425,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 84}},
 '2026-07-17 23:00:00': {'temperature': {'2m': 293.9,
   'sol': 294.4,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101660},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 47.4},
  'vent_moyen': {'10m': 9.1},
  'vent_rafales': {'10m': 22.2},
  'vent_direction': {'10m': 349},
  'iso_zero': 3398,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 16}},
 '2026-07-18 02:00:00': {'temperature': {'2m': 291.5,
   'sol': 292.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101720},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 54.7},
  'vent_moyen': {'10m': 9.4},
  'vent_rafales': {'10m': 15.8},
  'vent_direction': {'10m': 353},
  'iso_zero': 3369,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 38}},
 '2026-07-18 05:00:00': {'temperature': {'2m': 290.6,
   'sol': 290.8,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101710},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 60.6},
  'vent_moyen': {'10m': 9.5},
  'vent_rafales': {'10m': 21.5},
  'vent_direction': {'10m': 351},
  'iso_zero': 3398,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 65}},
 '2026-07-18 08:00:00': {'temperature': {'2m': 291,
   'sol': 289.8,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101790},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 65.9},
  'vent_moyen': {'10m': 9.3},
  'vent_rafales': {'10m': 16.3},
  'vent_direction': {'10m': 388},
  'iso_zero': 3379,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 70}},
 '2026-07-18 11:00:00': {'temperature': {'2m': 297.9,
   'sol': 295.5,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101820},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 39.6},
  'vent_moyen': {'10m': 9.1},
  'vent_rafales': {'10m': 12.3},
  'vent_direction': {'10m': 357},
  'iso_zero': 3354,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 5}},
 '2026-07-18 14:00:00': {'temperature': {'2m': 302.3,
   'sol': 299.7,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101670},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 26.9},
  'vent_moyen': {'10m': 9.8},
  'vent_rafales': {'10m': 12.3},
  'vent_direction': {'10m': 354},
  'iso_zero': 3312,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 5}},
 '2026-07-18 17:00:00': {'temperature': {'2m': 303.5,
   'sol': 301.9,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101530},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 23},
  'vent_moyen': {'10m': 9.3},
  'vent_rafales': {'10m': 11.8},
  'vent_direction': {'10m': 359},
  'iso_zero': 3137,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 38}},
 '2026-07-18 20:00:00': {'temperature': {'2m': 302.1,
   'sol': 301.5,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101470},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 24},
  'vent_moyen': {'10m': 19.2},
  'vent_rafales': {'10m': 20.2},
  'vent_direction': {'10m': 368},
  'iso_zero': 3232,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 52}},
 '2026-07-18 23:00:00': {'temperature': {'2m': 294.9,
   'sol': 294.5,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101750},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 40},
  'vent_moyen': {'10m': 22.5},
  'vent_rafales': {'10m': 42.5},
  'vent_direction': {'10m': 392},
  'iso_zero': 3248,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 70}},
 '2026-07-19 02:00:00': {'temperature': {'2m': 289.6,
   'sol': 289.1,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101800},
  'pluie': 0.5,
  'pluie_convective': 0.3,
  'humidite': {'2m': 70.8},
  'vent_moyen': {'10m': 20.4},
  'vent_rafales': {'10m': 43.7},
  'vent_direction': {'10m': 417},
  'iso_zero': 3120,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 75}},
 '2026-07-19 05:00:00': {'temperature': {'2m': 286.8,
   'sol': 286.7,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101950},
  'pluie': 0.1,
  'pluie_convective': 0.1,
  'humidite': {'2m': 79.3},
  'vent_moyen': {'10m': 13.3},
  'vent_rafales': {'10m': 30},
  'vent_direction': {'10m': 382},
  'iso_zero': 2954,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 82}},
 '2026-07-19 08:00:00': {'temperature': {'2m': 287.5,
   'sol': 286.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102040},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 75.6},
  'vent_moyen': {'10m': 17},
  'vent_rafales': {'10m': 36},
  'vent_direction': {'10m': 383},
  'iso_zero': 3014,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 45}},
 '2026-07-19 11:00:00': {'temperature': {'2m': 293.6,
   'sol': 290.8,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102140},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 40.2},
  'vent_moyen': {'10m': 16.6},
  'vent_rafales': {'10m': 22},
  'vent_direction': {'10m': 387},
  'iso_zero': 3121,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 0}},
 '2026-07-19 14:00:00': {'temperature': {'2m': 298.2,
   'sol': 295,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102080},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 24.4},
  'vent_moyen': {'10m': 14.1},
  'vent_rafales': {'10m': 17.7},
  'vent_direction': {'10m': 377},
  'iso_zero': 3255,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 1}},
 '2026-07-19 17:00:00': {'temperature': {'2m': 300.3,
   'sol': 297.7,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 101990},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 18.6},
  'vent_moyen': {'10m': 17},
  'vent_rafales': {'10m': 18.8},
  'vent_direction': {'10m': 379},
  'iso_zero': 3361,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 7}},
 '2026-07-19 20:00:00': {'temperature': {'2m': 298.1,
   'sol': 296.9,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102060},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 21.2},
  'vent_moyen': {'10m': 21.2},
  'vent_rafales': {'10m': 19.6},
  'vent_direction': {'10m': 375},
  'iso_zero': 3335,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 40}},
 '2026-07-19 23:00:00': {'temperature': {'2m': 292.2,
   'sol': 291.4,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102260},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 37},
  'vent_moyen': {'10m': 21.4},
  'vent_rafales': {'10m': 40.9},
  'vent_direction': {'10m': 378},
  'iso_zero': 3317,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 95}},
 '2026-07-20 02:00:00': {'temperature': {'2m': 288.2,
   'sol': 287.5,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102340},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 56.1},
  'vent_moyen': {'10m': 16.4},
  'vent_rafales': {'10m': 36.8},
  'vent_direction': {'10m': 383},
  'iso_zero': 3232,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 98}},
 '2026-07-20 05:00:00': {'temperature': {'2m': 284.5,
   'sol': 284.8,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102320},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 79.6},
  'vent_moyen': {'10m': 12.2},
  'vent_rafales': {'10m': 32.6},
  'vent_direction': {'10m': 379},
  'iso_zero': 3130,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 44}},
 '2026-07-20 08:00:00': {'temperature': {'2m': 286,
   'sol': 284.4,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102410},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 74.4},
  'vent_moyen': {'10m': 15},
  'vent_rafales': {'10m': 33.5},
  'vent_direction': {'10m': 384},
  'iso_zero': 3116,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 36}},
 '2026-07-20 11:00:00': {'temperature': {'2m': 292.9,
   'sol': 289.9,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102400},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 41.8},
  'vent_moyen': {'10m': 17.5},
  'vent_rafales': {'10m': 23.8},
  'vent_direction': {'10m': 388},
  'iso_zero': 3077,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 2}},
 '2026-07-20 14:00:00': {'temperature': {'2m': 297.9,
   'sol': 294.7,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102280},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 25.1},
  'vent_moyen': {'10m': 17.2},
  'vent_rafales': {'10m': 22.8},
  'vent_direction': {'10m': 381},
  'iso_zero': 3189,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 1}},
 '2026-07-20 17:00:00': {'temperature': {'2m': 299.8,
   'sol': 297,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102200},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 21.4},
  'vent_moyen': {'10m': 18.6},
  'vent_rafales': {'10m': 22.9},
  'vent_direction': {'10m': 389},
  'iso_zero': 3274,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 0}},
 '2026-07-20 20:00:00': {'temperature': {'2m': 298.5,
   'sol': 297.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102200},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 25.3},
  'vent_moyen': {'10m': 18.5},
  'vent_rafales': {'10m': 24.1},
  'vent_direction': {'10m': 390},
  'iso_zero': 3020,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 4}},
 '2026-07-20 23:00:00': {'temperature': {'2m': 292.9,
   'sol': 292.1,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102430},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 37.6},
  'vent_moyen': {'10m': 21.5},
  'vent_rafales': {'10m': 42.2},
  'vent_direction': {'10m': 375},
  'iso_zero': 3126,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 3}},
 '2026-07-21 02:00:00': {'temperature': {'2m': 288.5,
   'sol': 287.9,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102490},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 60.5},
  'vent_moyen': {'10m': 16},
  'vent_rafales': {'10m': 38.7},
  'vent_direction': {'10m': 380},
  'iso_zero': 3356,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 2}},
 '2026-07-21 05:00:00': {'temperature': {'2m': 286.1,
   'sol': 285.6,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102460},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 86.9},
  'vent_moyen': {'10m': 14.7},
  'vent_rafales': {'10m': 37.1},
  'vent_direction': {'10m': 369},
  'iso_zero': 3618,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 0}},
 '2026-07-21 08:00:00': {'temperature': {'2m': 287.6,
   'sol': 285.9,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102520},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 81.5},
  'vent_moyen': {'10m': 17},
  'vent_rafales': {'10m': 34.7},
  'vent_direction': {'10m': 376},
  'iso_zero': 3643,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 5}},
 '2026-07-21 11:00:00': {'temperature': {'2m': 294.3,
   'sol': 291.2,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102490},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 47.2},
  'vent_moyen': {'10m': 15.2},
  'vent_rafales': {'10m': 17.3},
  'vent_direction': {'10m': 382},
  'iso_zero': 3826,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 0}},
 '2026-07-21 14:00:00': {'temperature': {'2m': 298.7,
   'sol': 295.4,
   '500hPa': 273.2,
   '850hPa': 273.2},
  'pression': {'niveau_de_la_mer': 102330},
  'pluie': 0,
  'pluie_convective': 0,
  'humidite': {'2m': 31.5},
  'vent_moyen': {'10m': 12},
  'vent_rafales': {'10m': 14.8},
  'vent_direction': {'10m': 379},
  'iso_zero': 3989,
  'risque_neige': 'non',
  'cape': 0,
  'nebulosite': {'haute': 0, 'moyenne': 0, 'basse': 0, 'totale': 0}},
 '2026-07-21 17:00:00': {'temperature': {'2m': 301.1,
   'sol': 298.4,
   '500hPa': 273.2,

In [67]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://api.open-meteo.com/v1/forecast"
params = {
	"latitude": 45.7491,
	"longitude": 4.8479,
	"hourly": ["temperature_2m", "relative_humidity_2m", "rain", "surface_pressure", "wind_speed_10m"],
	"timezone": "Europe/London",
	"past_days": 7,
	"forecast_days": 1,
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
hourly_rain = hourly.Variables(2).ValuesAsNumpy()
hourly_surface_pressure = hourly.Variables(3).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(4).ValuesAsNumpy()

hourly_data = {
	"date": pd.date_range(
		start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
		end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = hourly.Interval()),
		inclusive = "left"
	).tz_convert(response.Timezone().decode())
}

hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["rain"] = hourly_rain
hourly_data["surface_pressure"] = hourly_surface_pressure
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m

hourly_dataframe = pd.DataFrame(data = hourly_data)
print("\nHourly data\n", hourly_dataframe)

Coordinates: 45.7400016784668°N 4.839999675750732°E
Elevation: 176.0 m asl
Timezone: b'Europe/London'b'GMT+1'
Timezone difference to GMT+0: 3600s

Hourly data
                          date  temperature_2m  relative_humidity_2m  rain  \
0   2026-07-09 00:00:00+01:00       27.513000                  40.0   0.0
1   2026-07-09 01:00:00+01:00       26.863001                  43.0   0.0
2   2026-07-09 02:00:00+01:00       26.163000                  46.0   0.0
3   2026-07-09 03:00:00+01:00       25.413000                  49.0   0.0
4   2026-07-09 04:00:00+01:00       24.863001                  49.0   0.0
..                        ...             ...                   ...   ...
187 2026-07-16 19:00:00+01:00       23.263000                  67.0   2.1
188 2026-07-16 20:00:00+01:00       22.913000                  72.0   0.1
189 2026-07-16 21:00:00+01:00       22.613001                  72.0   0.0
190 2026-07-16 22:00:00+01:00       22.463001                  74.0   0.0
191 2026-07-16 23:00:00+01:00       21.963001                  78.0   0.0

     surface_pressure  wind_speed_10m
0          995.333679       10.315115
1          994.996765       10.948973
2          995.342224       11.792404
3          994.998108       11.384198
4          994.667480       11.019764
..                ...             ...
187        996.323425        8.654986
188        995.515747        2.305125
189        996.082947        5.495161
190        997.640808       10.105681
191        998.096436        7.568566

[192 rows x 6 columns]

In [71]:
hourly_dataframe

,date,temperature_2m,relative_humidity_2m,rain,surface_pressure,wind_speed_10m
0,2026-07-09 00:00:00+01:00,27.513000,40.0,0.0,995.333679,10.315115
1,2026-07-09 01:00:00+01:00,26.863001,43.0,0.0,994.996765,10.948973
2,2026-07-09 02:00:00+01:00,26.163000,46.0,0.0,995.342224,11.792404
3,2026-07-09 03:00:00+01:00,25.413000,49.0,0.0,994.998108,11.384198
4,2026-07-09 04:00:00+01:00,24.863001,49.0,0.0,994.667480,11.019764
...,...,...,...,...,...,...
187,2026-07-16 19:00:00+01:00,23.263000,67.0,2.1,996.323425,8.654986
188,2026-07-16 20:00:00+01:00,22.913000,72.0,0.1,995.515747,2.305125
189,2026-07-16 21:00:00+01:00,22.613001,72.0,0.0,996.082947,5.495161
190,2026-07-16 22:00:00+01:00,22.463001,74.0,0.0,997.640808,10.105681
191,2026-07-16 23:00:00+01:00,21.963001,78.0,0.0,998.096436,7.568566