In [37]:
import pandas as pd
import numpy as np
import mlflow
from sklearn.linear_model import LinearRegression

In [53]:
df = pd.read_parquet('../data/final_datasets/datasets_linear_models/conso_v1_linear.parquet')

In [54]:
df['Consommation'] = df['Consommation'].shift(-1)

In [56]:
df = df.dropna()

In [58]:
df

,Consommation,Zone_A,Zone_B,Zone_C,Vacances de la Toussaint,Vacances de Noël,Vacances d'Hiver,Vacances de Printemps,Vacances d'Été,public_holidays,...,is_weekend_x_season_Summer,is_holiday_x_season_Summer,hour_x_season_Winter,is_weekend_x_season_Winter,is_holiday_x_season_Winter,temp_x_humidity,temp_x_wind,humidity_x_wind,HDD,CDD
168,83800.0,0,0,0,0,0,0,0,0,0,...,0,0,12.0,0,0,1.654045,0.067617,2.170722,17.773015,0.0
169,84185.0,0,0,0,0,0,0,0,0,0,...,0,0,12.5,0,0,1.710339,0.067872,2.063686,17.762828,0.0
170,82959.0,0,0,0,0,0,0,0,0,0,...,0,0,13.0,0,0,1.765092,0.078584,2.266992,17.752642,0.0
171,82055.0,0,0,0,0,0,0,0,0,0,...,0,0,13.5,0,0,1.789764,0.072393,2.024652,17.747029,0.0
172,81056.0,0,0,0,0,0,0,0,0,0,...,0,0,14.0,0,0,1.813754,0.084511,2.292404,17.741417,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70122,63946.0,0,0,0,0,0,0,0,0,0,...,0,0,21.0,0,0,2.760719,0.126087,2.769477,17.645474,0.0
70123,63063.0,0,0,0,0,0,0,0,0,0,...,0,0,21.5,0,0,2.723025,0.100193,2.225680,17.649882,0.0
70124,63816.0,0,0,0,0,0,0,0,0,0,...,0,0,22.0,0,0,2.685415,0.141657,3.182922,17.654291,0.0
70125,65437.0,0,0,0,0,0,0,0,0,0,...,0,0,22.5,0,0,2.625996,0.096355,2.231863,17.663294,0.0
70126,65159.0,0,0,0,0,0,0,0,0,0,...,0,0,23.0,0,0,2.566014,0.126100,3.013091,17.672296,0.0

### Train test split  
We make sure to not shuffle the dataset and split it by the year

In [59]:
train_set = df[df['year'] < 2024]
test_set = df[df['year'] == 2024]

X_train = train_set.drop(["Consommation"], axis=1)
Y_train = train_set[["Consommation"]]

X_test = test_set.drop(["Consommation"], axis=1)
Y_test = test_set[['Consommation']]

In [60]:
Y_test

       Consommation
52560       55167.0
52561       53183.0
52562       53165.0
52563       53088.0
52564       53077.0
...             ...
70122       63946.0
70123       63063.0
70124       63816.0
70125       65437.0
70126       65159.0

[17567 rows x 1 columns]

In [61]:
lr = LinearRegression().fit(X_train, Y_train)

In [62]:
score = lr.score(X_test, Y_test)

In [63]:
score

0.9961206210986688

In [38]:
np.sort(lr.coef_)

array([[-1.16514160e-07, -9.88502225e-08, -8.76258855e-08,
        -8.08108618e-08, -6.98312937e-08, -6.47048021e-08,
        -5.87751760e-08, -3.12514742e-08, -3.03627895e-08,
        -1.31158861e-08, -1.31019042e-08, -9.74992374e-09,
        -8.51805813e-09, -8.21303178e-09, -7.35678746e-09,
        -6.55297145e-09, -5.44432530e-09, -5.21751635e-09,
        -4.66245257e-09, -4.22898852e-09, -3.87514806e-09,
        -3.75841998e-09, -3.22784573e-09, -2.99930440e-09,
        -2.90908943e-09, -2.17540719e-09, -1.97402996e-09,
        -1.96714306e-09, -1.94261572e-09, -1.85457743e-09,
        -1.63055018e-09, -1.56020661e-09, -9.45166012e-10,
        -3.37486857e-10, -3.12989014e-10, -1.59124680e-10,
        -3.75747719e-11, -1.94214740e-11, -9.62293995e-12,
        -7.04978573e-12,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.69406589e-21,  1.35525272e-20,  2.22044605e-16,
         3.94617492e-12,  7.84038546e-12,  1.15959971e-11,
         1.47253967e-11,  2.45065343e-10,  3.12989014e-10,
         4.15493801e-10,  1.30011831e-09,  1.42112564e-09,
         2.83654969e-09,  3.66456714e-09,  5.04463850e-09,
         5.18757601e-09,  5.28339320e-09,  5.44752676e-09,
         9.27237012e-09,  1.15683496e-08,  1.23261862e-08,
         1.45282102e-08,  1.52597925e-08,  1.67443799e-08,
         1.69924070e-08,  1.81125077e-08,  2.05024345e-08,
         3.16268918e-08,  3.30844153e-08,  3.73997515e-08,
         4.68160319e-08,  7.46995229e-08,  8.16921476e-08,
         9.69780643e-08,  1.40972855e-07,  1.62500793e-07,
         9.42391715e-06,  1.02132155e-05,  5.00000000e-01,
         5.00000000e-01,  5.00000000e-01,  5.00000000e-01]])